source '/Users/cweymann/workspace/Lab/localPrivateRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'FrameworkB_Objc_DependencyIssue_Example' do
  pod 'FrameworkB_Objc_DependencyIssue', :path => '../'

  target 'FrameworkB_Objc_DependencyIssue_Tests' do
    inherit! :search_paths
  end
end

#post_install do |installer|
#	installer.pods_project.build_configurations.each do |config|
#		config.build_settings[‘EXCLUDED_ARCHS[sdk=iphonesimulator*]’] = ‘arm64’
#	end
#end
